name: bob_app
packages:
  - apps/**
  - packages/**

scripts:
  generate:all:
    steps:
      - melos run generate:serverpod --no-select
      - melos run generate:exports
    description: Generate serverpod classes and update shared exports

  generate:exports:
    run: fvm dart run tools/generate_shared_exports.dart
    description: Update shared model exports

  generate:serverpod:
    description: Generate Serverpod client
    exec: serverpod generate
    packageFilters:
      scope: bob_be_server

  dev:server:
    run: serverpod run

  dev:frontend:
    run: fvm flutter run


  deps:get:
    exec: |
      if grep -q "flutter" pubspec.yaml; then
        fvm flutter pub get
      else
        dart pub get
      fi
    packageFilters:
      ignore: bob_app  # Skip workspace root
